var Stub = {};
Stub.articles = [
    {
        id: '11',
        title: 'Best article ever',
        fullName: 'Sheila Ellis',
        photo: 'https://randomuser.me/api/portraits/med/women/71.jpg',
        img: 'https://d262ilb51hltx0.cloudfront.net/fit/t/1000/300/1*OhIhVAgh9FhZjKpdKk0UeQ.jpeg',
        ageStr: '2 weeks ago',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lengthStr: '2 min reading',
    },
    {
        id: '12',
        title: 'Best article ever',
        fullName: 'Sheila Ellis',
        photo: 'https://randomuser.me/api/portraits/med/women/72.jpg',
        img: 'https://d262ilb51hltx0.cloudfront.net/fit/t/1000/300/1*TV6vEgojNX8QFufqzwozeA.jpeg',
        ageStr: '2 weeks ago',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lengthStr: '12 min reading',
    },
    {
        id: '13',
        title: 'Best article ever',
        fullName: 'Sheila Ellis',
        photo: 'https://randomuser.me/api/portraits/med/women/73.jpg',
        img: 'https://d262ilb51hltx0.cloudfront.net/fit/t/1000/300/1*cHrXjIht9o3YF2iqIDSLIg.png',
        ageStr: '2 weeks ago',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lengthStr: '7 min reading',
    },
    {
        id: '14',
        title: 'Best article ever',
        fullName: 'Sheila Ellis',
        photo: 'https://randomuser.me/api/portraits/med/women/74.jpg',
        img: 'https://d262ilb51hltx0.cloudfront.net/fit/t/1000/300/1*OhIhVAgh9FhZjKpdKk0UeQ.jpeg',
        ageStr: '2 weeks ago',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lengthStr: '10 min reading',
    },
    {
        id: '15',
        title: 'Best article ever',
        fullName: 'Sheila Ellis',
        photo: 'https://randomuser.me/api/portraits/med/women/75.jpg',
        img: 'https://d262ilb51hltx0.cloudfront.net/fit/t/1000/300/1*OhIhVAgh9FhZjKpdKk0UeQ.jpeg',
        ageStr: '2 weeks ago',
        text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        lengthStr: '11 min reading',
    },
];
